apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-deployment
  labels:
    app: mongodb
 spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
     spec: 
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017 #defalut port value of a mongodb server. check at mongo dockerhub
          env: 
   #username and password shouldn't get here. so what we gonna do is create a secret yml file.
          - name: MONGO_INITDB_ROOT_USERNAME
            value:
          - name: MONGO_INITDB_ROOT_PASSWORD
            value:
            
        
    
