apiVersion: v1
kind: secret #it has secret values so that it cannot get stored in the repository
metadata:
  name: mongodb-secret # any random name can be given
type: Opaque # default for arbitrary key-value pairs. we can use TLS certs etc here.
data: #the actual contents of key value pair. these shouldn't be plain text. must be base64 encoded
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: UGFzc3dvcmQ=
  #storing the data in a "Secret" component doesn't automatically make it secure, there are built in mechanism (like encryption) for 
  #basic security, which are not enabled by default.
