apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-deployment
  labels:
    app: mongodb
 spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
     spec: 
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017 #defalut port value of a mongodb server. check at mongo dockerhub
          env: 
   #username and password shouldn't get here. so what we gonna do is create a secret yml file.
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: #as we are referencing from secret yaml. which has to be already deployed
              secretKeyRef:
                name: mongodb-secret  #this name should be the name of kind secret under metadata
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: #as we are referencing from secret yaml. which has to be already deployed
              secretKeyRef:
                name: mongodb-secret  #this name should be the name of kind secret under metadata
                key: mongo-root-password
            
 # we can write multiple configuration/ components in a single yaml by using the seperator 
 
 ---
 
 apiVersion: v1
 kind: Service
 metadata:
  name: mongodb-service # your own random service name
 spec:
  selector:
    app: mongodb # connect to pod through label in the line 14. these two names should match always
    ports:
      protocol: TCP
      port: 27017 #service port
      targetPort: 27017 # contianerPort of deployment (line no 21)
    # port and targetPort can be different. but here i am mkaing same for understanding.
    # the targetPort is where you can access your application for ex: 172.17.0.6:27017. the 172.1.0.6 is pod ip address
    #
 
    
