apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
 spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express
template:
  metadata:
    labels:
      app: mongo-express
   spec:
    containers:
    - name: mongo-express
      image: mongo-express
      ports:
      - containerPort: 8081
      env:
      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        valueFrom: mongodb-secret
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-username
      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        valueFrom: mongodb-secret
          secretKeyRef:
            name: mongodb-secret
            key: mongo-root-password
       - name: ME_CONFIG_MONGODB_SERVER
        value: # the value of server url can added here but we will use configMap so that all services can user
        #a centralised source url .
      
